version: '3.9'
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_FILE=/usr/src/app/data/keys.db
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped